# Generated by Django 2.1.2 on 2018-12-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
