# Generated by Django 2.1.2 on 2018-12-10 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20181210_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='tienda',
        ),
        migrations.AddField(
            model_name='productos',
            name='tienda',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='compras.Tienda'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='tienda',
            name='ciudad',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='compras.Ciudad'),
            preserve_default=False,
        ),
    ]
